### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [tessmero/tc359_project7_tessmero#1]
This repo looks empty. Did you forget to `git push origin master`?

**Comment by tessmero** [comment]
My mistake, fixed now

**Comment by chrisvfritz** [comment]
Looking much better. :smiley: I do see some hard-tabs in `app.rb` though, rather than the standard two-space soft-tabs. The [resources on this page](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) should help you fix this. 

Let me know when it's updated and I'll take a final look.

**Comment by tessmero** [comment]
Updated

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
